### ISSUE TITLE
biotech issue

### ISSUE THREAD

**Issue by KrzysztofKowalski** [SonicTHI/SaveOurShip2Experimental#10]
https://gist.github.com/HugsLibRecordKeeper/dfbca239703d879dcc61679de24755f5

cannot spawn hologram even if research is completed

**Comment by KrzysztofKowalski** [comment]
Error while determining if SoSHologramRace11967 should have Need Chemical_Alcohol: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) RimWorld.LifeStageWorker_HumanlikeAdult.RimWorld.LifeStageWorker_HumanlikeAdult.Notify_LifeStageStarted_Patch0(RimWorld.LifeStageWorker_HumanlikeAdult,Verse.Pawn,RimWorld.LifeStageDef)
  at Verse.Pawn_AgeTracker.RecalculateLifeStageIndex () [0x00127] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at Verse.Pawn_AgeTracker.get_CurLifeStageIndex () [0x00009] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at Verse.Pawn_AgeTracker.get_CurLifeStageRace () [0x00000] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at Verse.Pawn_AgeTracker.get_CurLifeStage () [0x00000] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at Verse.Pawn.get_DevelopmentalStage () [0x00012] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at (wrapper dynamic-method) RimWorld.Pawn_NeedsTracker.RimWorld.Pawn_NeedsTracker.ShouldHaveNeed_Patch3(RimWorld.Pawn_NeedsTracker,RimWorld.NeedDef)
  at RimWorld.Pawn_NeedsTracker.AddOrRemoveNeedsAsAppropriate () [0x00016] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
RimWorld.Pawn_NeedsTracker:AddOrRemoveNeedsAsAppropriate ()
RimWorld.Pawn_NeedsTracker:.ctor (Verse.Pawn)
(wrapper dynamic-method) RimWorld.PawnComponentsUtility:RimWorld.PawnComponentsUtility.CreateInitialComponents_Patch1 (Verse.Pawn)
Verse.PawnGenerator:TryGenerateNewPawnInternal (Verse.PawnGenerationRequest&,string&,bool,bool)
(wrapper dynamic-method) Verse.PawnGenerator:Verse.PawnGenerator.GenerateNewPawnInternal_Patch5 (Verse.PawnGenerationRequest&)
Verse.PawnGenerator:GenerateOrRedressPawnInternal (Verse.PawnGenerationRequest)
(wrapper dynamic-method) Verse.PawnGenerator:Verse.PawnGenerator.GeneratePawn_Patch1 (Verse.PawnGenerationRequest)
RimWorld.CompBuildingConsciousness:GenerateAIPawn ()
RimWorld.CompBuildingConsciousness:<CompGetGizmosExtra>b__19_2 ()
Verse.Command_Action:ProcessInput (UnityEngine.Event)
Verse.GizmoGridDrawer:DrawGizmoGrid (System.Collections.Generic.IEnumerable`1<Verse.Gizmo>,single,Verse.Gizmo&,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>)
(wrapper dynamic-method) RimWorld.InspectGizmoGrid:RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0 (System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos ()
RimWorld.InspectPaneUtility:ExtraOnGUI (RimWorld.IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI ()
Verse.WindowStack:WindowStackOnGUI ()
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch1 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)

**Comment by KrzysztofKowalski** [comment]
No shuffled Adulthood found for holographic avatar of PlayerColony. Choosing random.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
(wrapper dynamic-method) RimWorld.PawnBioAndNameGenerator:RimWorld.PawnBioAndNameGenerator.FillBackstorySlotShuffled_Patch1 (Verse.Pawn,RimWorld.BackstorySlot,System.Collections.Generic.List`1<RimWorld.BackstoryCategoryFilter>,RimWorld.FactionDef,System.Nullable`1<RimWorld.BackstorySlot>)
RimWorld.PawnBioAndNameGenerator:GiveShuffledBioTo (Verse.Pawn,RimWorld.FactionDef,string,System.Collections.Generic.List`1<RimWorld.BackstoryCategoryFilter>,bool,bool,RimWorld.XenotypeDef)
(wrapper dynamic-method) RimWorld.PawnBioAndNameGenerator:RimWorld.PawnBioAndNameGenerator.GiveAppropriateBioAndNameTo_Patch1 (Verse.Pawn,string,RimWorld.FactionDef,bool,bool,RimWorld.XenotypeDef)
Verse.PawnGenerator:TryGenerateNewPawnInternal (Verse.PawnGenerationRequest&,string&,bool,bool)
(wrapper dynamic-method) Verse.PawnGenerator:Verse.PawnGenerator.GenerateNewPawnInternal_Patch5 (Verse.PawnGenerationRequest&)
Verse.PawnGenerator:GenerateOrRedressPawnInternal (Verse.PawnGenerationRequest)
(wrapper dynamic-method) Verse.PawnGenerator:Verse.PawnGenerator.GeneratePawn_Patch1 (Verse.PawnGenerationRequest)
RimWorld.CompBuildingConsciousness:GenerateAIPawn ()
RimWorld.CompBuildingConsciousness:<CompGetGizmosExtra>b__19_2 ()
Verse.Command_Action:ProcessInput (UnityEngine.Event)
Verse.GizmoGridDrawer:DrawGizmoGrid (System.Collections.Generic.IEnumerable`1<Verse.Gizmo>,single,Verse.Gizmo&,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>)
(wrapper dynamic-method) RimWorld.InspectGizmoGrid:RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0 (System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos ()
RimWorld.InspectPaneUtility:ExtraOnGUI (RimWorld.IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI ()
Verse.WindowStack:WindowStackOnGUI ()
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch1 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)

**Comment by KrzysztofKowalski** [comment]
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.Pawn_StoryTracker.set_Childhood (RimWorld.BackstoryDef value) [0x00012] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at RimWorld.CompBuildingConsciousness.GenerateAIPawn () [0x00094] in <f86017e2062145b39b5077a249a20b8b>:0 
  at RimWorld.CompBuildingConsciousness.<CompGetGizmosExtra>b__19_2 () [0x00001] in <f86017e2062145b39b5077a249a20b8b>:0 
  at Verse.Command_Action.ProcessInput (UnityEngine.Event ev) [0x00007] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at Verse.GizmoGridDrawer.DrawGizmoGrid (System.Collections.Generic.IEnumerable`1[T] gizmos, System.Single startX, Verse.Gizmo& mouseoverGizmo, System.Func`2[T,TResult] customActivatorFunc, System.Func`2[T,TResult] highlightFunc, System.Func`2[T,TResult] lowlightFunc) [0x00707] in <a083023a4c8e4da38c31ca2cf71822b5>:0 
  at (wrapper dynamic-method) RimWorld.InspectGizmoGrid.RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0(System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&) currentSelectable: null
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
Verse.Log:ErrorOnce (string,int)
(wrapper dynamic-method) RimWorld.InspectGizmoGrid:RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0 (System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos ()
RimWorld.InspectPaneUtility:ExtraOnGUI (RimWorld.IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI ()
Verse.WindowStack:WindowStackOnGUI ()
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch1 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)

**Comment by GC919YT** [comment]
I'm not a game expert but I think the textures may be missing as I spawned a hologram with dev mode and it looked as if there was a missing texture

**Comment by DarianLStephens** [comment]
There was a bug a short time after Biotech's release which made some pawns have a magenta square over them when... growing up, I think.
Maybe the same thing is happening here?

**Comment by USMP-lancer** [comment]
i have played with a later version, the issue stated here is still a thing, its specifically an issue with persona core holograms, they do not spawn, afterlife holograms seem fine, i have had an issue where a archotech hologram loses the archotech holgram hediff, alongside every other benefit of being a hologram(no idea how to do a fix with dev mode, adding the hediff simply removes it)

**Comment by USMP-lancer** [comment]
while they are in this broken state their holo apparel is also gone
