### ISSUE TITLE
REALLY strange bugs about the Nuclear Engine and Thrust/Weight ratio

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#100]
1:No matter what and how, only 8 of all Nuclear Engines can work.
2: There may be issues with the weight \ thrust ratio algorithm.
https://www.bilibili.com/video/BV1ga4y1q78d
↑ In this video, you can see that the hostile Colossus Class Dreadnought does not have the first issue. At 00min08s, 12 Nuclear Engines at the back of it blow beautiful flame out. 

https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/2ce87036-9252-4e6c-9eb1-baa4c70c7f61

↑ This is a video about the bugs, I'm sorry for my bad English and recording skills, but I really love this mod and you guys.
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13818082/Player.log)
and this is the log. I'm sorry that I didn't remove those mods which are maybe too much, but it seems that they are working together happily. It isn't likely possible that they work against each other, I mean.

**Comment by SonicTHI** [comment]
Should be fixed now. If not, let me know.

**Comment by WhiteGiverMa** [comment]
The first bug I reported gets fixed exactly, **but I'm sorry to tell u that the second one not yet.** In the video above, I have 6 rocket engines and 17 nuclear engines, my thrust should be 6x1000+17x3000=**57000**. My weight is at **26768**. So my **Thrust/Weight ratio should be 2.129. But it appears 1.617.**
Btw, I dont know what 'bcount7265' means in this info. May I get some explaining?
Anyway, thanks for your contribution. We all hope and believe this mod will be better.
![屏幕截图 2024-01-04 095054](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/5520ff43-e1ee-479a-8c6b-6074eb5c243c)
 (I remove and rebuild all engines and check the thrust/weight ratio again. I'm sure it isn't fixed.)

**Comment by WhiteGiverMa** [comment]
> Should be fixed now. If not, let me know.

Oh sorry guy, the bug about weight/thrust ratio is still here. I provide some detail here.

**Comment by SonicTHI** [comment]
Right, i swapped the readout to show the actual combat t/w which is calculated differently than thrust/weight - see dev sheet. So only the weight value is currently wrong but at the same time correct for takeoff purposes which work differently. I ll see what i can do.

**Comment by WhiteGiverMa** [comment]
> Right, i swapped the readout to show the actual combat t/w which is calculated differently than thrust/weight - see dev sheet. So only the weight value is currently wrong but at the same time correct for takeoff purposes which work differently. I ll see what i can do.
Thank you guy, waiting for your good news✧(≖ ◡ ≖✿)

**Comment by WhiteGiverMa** [comment]
> Right, i swapped the readout to show the actual combat t/w which is calculated differently than thrust/weight - see dev sheet. So only the weight value is currently wrong but at the same time correct for takeoff purposes which work differently. I ll see what i can do.

Thank you guy, waiting for your good news✧(≖ ◡ ≖✿)

**Comment by SonicTHI** [comment]
Fixed in V96f6.
