### ISSUE TITLE
When I approach more than 1 derelict, I can only retrieve one of them. 

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#102]
As the title.
![屏幕截图 2024-01-05 102133](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/cae1eabb-6cfe-495c-89fb-e63f53468a41)
![屏幕截图 2024-01-05 102140](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/7d08ebd6-b90a-4be4-adf9-968a77728c0a)
![屏幕截图 2024-01-05 102145](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/ffe94c3b-172a-49b7-b4d8-ade831f29c63)

**Comment by WhiteGiverMa** [comment]
Exactly: the earliest I approach.

**Comment by SonicTHI** [comment]
Fixed in V96f6.
