### ISSUE TITLE
Pawns won't do construction tasks actively

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#103]
https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/20cd5f75-181a-4feb-9780-8d8246f51bee

Sorry for my bad oral English skill...
In this video, I already had meterials to build a spinal barrel, but it seemed that my kawaii girls and lazy mechanoids didn't want to build it. As soon as I forced one of my girls to do, others and mechs followed to do too. This kind of phenomenon (I can't spell this word in the video) always appears. I heard that it's maybe about a mod called 'Achtung!', but I haven't used it at all.
Is my log needed, my dear guys?

Here is my modlist:
Version: 0
Mods:
- Id: brrainz.harmony
  Name: Harmony
  SteamWorkshopId: 2009463077
- Id: ludeon.rimworld
  Name: 核心 
  SteamWorkshopId: 0
- Id: ludeon.rimworld.royalty
  Name: 皇权
  SteamWorkshopId: 0
- Id: ludeon.rimworld.ideology
  Name: 文化
  SteamWorkshopId: 0
- Id: ludeon.rimworld.biotech
  Name: 生物技术
  SteamWorkshopId: 0
- Id: unlimitedhugs.hugslib
  Name: HugsLib
  SteamWorkshopId: 818773962
- Id: jaxe.bubbles
  Name: Interaction Bubbles
  SteamWorkshopId: 1516158345
- Id: fluffy.modmanager
  Name: Mod Manager
  SteamWorkshopId: 1507748539
- Id: fluffy.blueprints
  Name: Blueprints
  SteamWorkshopId: 708455313
- Id: caesarv6.damageindicators
  Name: Damage Indicators [1.4]
  SteamWorkshopId: 2016331497
- Id: smashphil.loadinginprogress
  Name: Loading In Progress
  SteamWorkshopId: 1975622772
- Id: uuugggg.buildfrominventory
  Name: Build From Inventory
  SteamWorkshopId: 1691419062
- Id: owlchemist.bettervanillamasking
  Name: Better Vanilla Masking
  SteamWorkshopId: 1736114368
- Id: nals.customportraits
  Name: '[NL] Custom Portraits'
  SteamWorkshopId: 1569605867
- Id: fluffy.medicaltab
  Name: Medical Tab
  SteamWorkshopId: 715565817
- Id: hatti.qualitybuilder
  Name: QualityBuilder
  SteamWorkshopId: 754637870
- Id: avilmask.commonsense
  Name: Common Sense
  SteamWorkshopId: 1561769193
- Id: brrainz.cameraplus
  Name: Camera+
  SteamWorkshopId: 867467808
- Id: jaxe.rimhud
  Name: RimHUD
  SteamWorkshopId: 1508850027
- Id: nals.dynamicportraits
  Name: '[NL] Dynamic Portraits'
  SteamWorkshopId: 2253730555
- Id: rimfridge.kv.rw
  Name: RimFridge Updated
  SteamWorkshopId: 2878183338
- Id: lwm.deepstorage
  Name: LWM's Deep Storage
  SteamWorkshopId: 1617282896
- Id: mehni.pickupandhaul
  Name: Pick Up And Haul
  SteamWorkshopId: 1279012058
- Id: kahdeg.killfeed
  Name: Killfeed
  SteamWorkshopId: 1362098265
- Id: krafs.levelup
  Name: Level Up!
  SteamWorkshopId: 1701592470
- Id: yoann.somemorejobs
  Name: Some more jobs
  SteamWorkshopId: 2245161494
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
  SteamWorkshopId: 761421485
- Id: void.charactereditor
  Name: Character Editor
  SteamWorkshopId: 1874644848
- Id: won.hair
  Name: Won hair_men
  SteamWorkshopId: 1879950403
- Id: won2.hair
  Name: 'Won hair_women '
  SteamWorkshopId: 1886150617
- Id: mehni.numbers
  Name: Numbers
  SteamWorkshopId: 1414302321
- Id: jintuzilamian.hairstyle.afuwomenshairstyles
  Name: AFU女士发型_Women's hairstyles
  SteamWorkshopId: 2020779666
- Id: jintuzilamian.hairstyle.afumenshairstyles
  Name: AFU男士发型_Men's hairstyles
  SteamWorkshopId: 2072106893
- Id: m0ek.novanillahair
  Name: No Vanilla Hair
  SteamWorkshopId: 1930877982
- Id: com.yayo.yayoani.continued
  Name: Yayo's Animation (Continued)
  SteamWorkshopId: 2877292196
- Id: nals.facialanimation
  Name: '[NL] Facial Animation - WIP'
  SteamWorkshopId: 1635901197
- Id: m00nl1ght.mappreview
  Name: Map Preview
  SteamWorkshopId: 2800857642
- Id: stm.shellabackgrounds
  Name: Shella Backgrounds
  SteamWorkshopId: 2853407446
- Id: savestoragesettings.kv.rw
  Name: '[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings [1.4]'
  SteamWorkshopId: 0
- Id: automatic.bionicicons
  Name: Bionic icons
  SteamWorkshopId: 1677616980
- Id: uuugggg.tdfindlib
  Name: TD Find Lib
  SteamWorkshopId: 2895299310
- Id: uuugggg.ctrlf
  Name: Ctrl F
  SteamWorkshopId: 2895300634
- Id: murmur.walllight
  Name: Wall Light
  SteamWorkshopId: 1423699208
- Id: visibleraidpoints.1trickpwnyta
  Name: Visible Raid Points
  SteamWorkshopId: 2562730174
- Id: chris.cutercatearreplacer
  Name: Cuter Biotech Cat/Dog Ear Replacer
  SteamWorkshopId: 2878864038
- Id: ih.clean.textures
  Name: Clean Textures
  SteamWorkshopId: 2865361569
- Id: falconne.bwm
  Name: Better Workbench Management
  SteamWorkshopId: 935982361
- Id: klr.gloomyhairmk2forked
  Name: Gloomy Hair mk2 FORKED[1.4]
  SteamWorkshopId: 2895002564
- Id: mlie.rangeddps
  Name: Ranged DPS (Continued)
  SteamWorkshopId: 2887818980
- Id: elif.bioniceyesoverlayremoval
  Name: '[ELIF] Bionic Eyes Overlay Removal'
  SteamWorkshopId: 2880879890
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
  SteamWorkshopId: 1446523594
- Id: com.github.alandariva.moreplanning
  Name: More Planning [1.4]
  SteamWorkshopId: 2551225702
- Id: legodude17.qualcolor
  Name: Quality Colors
  SteamWorkshopId: 2420141361
- Id: cat2002.showhair
  Name: '[CAT] Show Hair With Hats or Hide All Hats'
  SteamWorkshopId: 2879080074
- Id: rimsenal.hair
  Name: Rimsenal - Hair pack
  SteamWorkshopId: 725949967
- Id: wazz.ui.maz
  Name: MAZ Mass Assign Zone
  SteamWorkshopId: 2853717952
- Id: telardo.dragselect
  Name: DragSelect
  SteamWorkshopId: 2599942235
- Id: wvc.sergkart.biotech.moremechanoidsworkmodes
  Name: WVC - Work Modes
  SteamWorkshopId: 2888380373
- Id: community.psychology.unofficialupdate
  Name: Psychology (unofficial) v1.1-1.4
  SteamWorkshopId: 2016263135
- Id: sandy.rpgstyleinventory.avilmask.revamped
  Name: RPG Style Inventory Revamped
  SteamWorkshopId: 2478833213
- Id: krkr.rocketman
  Name: RocketMan - Performance Mod
  SteamWorkshopId: 2479389928
- Id: dubwise.dubsmintminimap
  Name: Dubs Mint Minimap
  SteamWorkshopId: 1662119905
- Id: peppsen.pmusic
  Name: P-Music
  SteamWorkshopId: 725130005
- Id: telardo.romanceontherim
  Name: Romance On The Rim
  SteamWorkshopId: 2654432921
- Id: roolo.almostthere
  Name: Almost There!
  SteamWorkshopId: 2372543327
- Id: tikubonn.dontblockdoor
  Name: Don't Block Door
  SteamWorkshopId: 1691076769
- Id: porio.tunnulerfix
  Name: Allow Tunnelers To Drill
  SteamWorkshopId: 2882915775
- Id: tammybee.appearanceclothes
  Name: Appearance clothes
  SteamWorkshopId: 1537867047
- Id: orion.xevarimhair
  Name: Xeva's Rimhair
  SteamWorkshopId: 705924057
- Id: jpt.speakup
  Name: SpeakUp
  SteamWorkshopId: 2502518544
- Id: nimrag.scenariosearchbar
  Name: Scenario Searchbars
  SteamWorkshopId: 3052467818
- Id: fluffy.followme
  Name: Follow Me
  SteamWorkshopId: 715759739
- Id: jangodsoul.simplestorage
  Name: '[JDS] Simple Storage'
  SteamWorkshopId: 1961098970
- Id: sarg.smartspeed
  Name: Smart Speed
  SteamWorkshopId: 1504723424
- Id: bbis.maidproject
  Name: '[SS]Maid Project'
  SteamWorkshopId: 1498756997
- Id: meltup.polyamorybeds.vanilla
  Name: Polyamory Beds (Vanilla Edition)
  SteamWorkshopId: 2008138191
- Id: gha.zh.psychology
  Name: Psychology (unofficial)_zh
  SteamWorkshopId: 2575318252
- Id: udon.masslovein
  Name: Mass Lovin'
  SteamWorkshopId: 2612846082
- Id: kentington.saveourship2
  Name: Save Our Ship 2
  SteamWorkshopId: 1909914131
- Id: uuugggg.tdsbugfixes
  Name: TDS Bug Fixes
  SteamWorkshopId: 2895035527
- Id: mlie.clutterdoors
  Name: ClutterDoors (Continued)
  SteamWorkshopId: 2678597932

**Comment by WhiteGiverMa** [comment]
Maybe this issue is listed in the dev sheet, but I can't surf it legally in my country. Maybe I can try some special ways.

**Comment by SonicTHI** [comment]
This does not look like an SOS2 issue, have you checked the home zone?
I ve put up a copy of the dev sheet here:
[SOS2.Experimental.xlsx](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13849791/SOS2.Experimental.xlsx)

Also, can you access wikia? ([sosv2.fandom.com](sosv2.fandom.com))

**Comment by WhiteGiverMa** [comment]
> This does not look like an SOS2 issue, have you checked the home zone? I ve put up a copy of the dev sheet here: [SOS2.Experimental.xlsx](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13849791/SOS2.Experimental.xlsx)
> 
> Also, can you access wikia? ([sosv2.fandom.com](sosv2.fandom.com))

When I restart my game, this issue disappear for a short time. But it 'll be back in a period. I 'll observe it for a longer.
Thank u guy, I 've got it‍ (・ω< )★
Yes, I can access it, but it seems that there's nothing in it OwO
