### ISSUE TITLE
Some issues and opinions about retrieving&salvaging

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#104]
Above all,**I'm not attempting to make you guys to bring us back to those days when we can get plenty of resources by one-click. I just want to tell you as a deep player, a video uploader on Bilibili.com with 0.8k fans, something I want to say from the bottom of my heart. And I want to fully respect you, The choices of how to deal with it belongs to you, but I think we players should have choices too.**
   Please imagine, you had a uphill battle with Dreadnought just now, it's time to do something to make up for the consuming. However, the derelict of Dreadnought is too large to be place in your map, so you have to abandon it upsetly. Or, there's an extreme way to retrieve it: first, luanch your boarding party; second, kill the rest of them on the derelict all; third, divide the derelict into several parts; lastly, retrieve these parts one by one. It's so troublesome, right?
   And retrieving also have one problem: It 'll bring all the hostile crew to your map. Although you have more than 15 pawns (too many pawns will cause laggy), to encounter so many enemies (usually mare than 40) is quite difficult, even with some turrets.
   But the old salvage system doesn't have these problem: pawns on hostlile ship will be serious injured when salvaging. And how many things we can retrieve only depends on the number of salvage bays, but not the rest place of the map. 
   On the Asteroid Base, because the asteroid occupied nearly 95% of the map, we can hardly retrieve anything.** 
   I said so many things here **not to criticise the retrieving system now, conversely, I really appriciate it, it brings more posibility to ship construction.**
   **In my opinion, the old salvage system and the retrieve system should be together, but the resources we get by one-click can be strictly limited. For instance, give it a factor of 60%(to removing, this is my advice).
  In this way, players' fulfillment can be satisfied, they will also be more willing to play this mod.
   Thanks.**
   And this is my Bilibili space: https://space.bilibili.com/357545524

**Comment by SonicTHI** [comment]
Something like this is already planned and you can already use the spinal disassembler to turn the enemy ship into resources.

**Comment by WhiteGiverMa** [comment]
> Something like this is already planned and you can already use the spinal disassembler to turn the enemy ship into resources.

Retrieving for Asteroid Bases is still a problem (┯_┯)

**Comment by WhiteGiverMa** [comment]
> Something like this is already planned and you can already use the spinal disassembler to turn the enemy ship into resources.

Hey, guy~ I have read the dev sheet carefully! I see a concept called 'Archobay', I think it's maybe something like the old salvage bay, right? But it's an archotech building, we can't get it easily, espescially in the early period of the game. So the problem about retreving on Asteroid Bases still exists!
emmm,I don't mean to annoy you, have a nice day✧(≖ ◡ ≖✿)
