### ISSUE TITLE
The problem about retrieving on Asteroid Bases still exists

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#105]
> Something like this is already planned and you can already use the spinal disassembler to turn the enemy ship into resources.

Hey, guy~ I have read the dev sheet carefully! I see a concept called 'Archobay', I think it's maybe something like the old salvage bay, right? But it's an archotech building, we can't get it easily, espescially in the early period of the game. So the problem about retrieving on Asteroid Bases still exists!
emmm,I don't mean to annoy you, have a nice day✧(≖ ◡ ≖✿)

_Originally posted by @WhiteGiverMa in https://github.com/SonicTHI/SaveOurShip2Experimental/issues/104#issuecomment-1879917661_

**Comment by SonicTHI** [comment]
Space starts are supposed to be harder than normal RW and were never properly balanced. This likely wont ever change.

**Comment by WhiteGiverMa** [comment]
> Space starts are supposed to be harder than normal RW and were never properly balanced. This likely wont ever change.

Maybe I don't express my meaning accurately QwQ, **The asteroid bases is in space, IN SPACE! But it can hardly retrieve anything because of the rest place of the map is not enough, it's too stupid!** (not insulting you, maybe you dear guys weren't aware of that, and you're too busy to experience your own mod.) **If just allow us to widen the map to contain a derelict, all will be change in this way!** I'm saying this nearly digging my heart out because I really like this mod and you guys, or I won't do this!……\ ( > < ) /
