### ISSUE TITLE
Uranium is hard to get in space

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#108]
In the past versions, we can easily get a lot of uranium by the old salvage bay. **But now, however, we can only get a few uranium by removing enemy's ship derelict. That's very strange. You see, by right, we should get uranium as much as the past.** 
I uploaded some videos on Bilibili and discussed this with some deep players like me, **and they all agree my opinion: uranium is strangely being less in space.**
Now the quantity of uranium is just enough if we often trade with factions. **But an important weapon, the symbol of capital ship armament, Artillery turret, its usage cost has become very expensive. Though sometimes I can afford it, but resources I stored decreases rapidly let my playing desire decreases too.**
I really love this mod and you guys, can you do something to change this please?✧(≖ ◡ ≖✿)

**Comment by SonicTHI** [comment]
There was a fuel multiplier on the cannons which resulted in lower shots per uranium and less uranium from dismantled enemy turrets. I ll change it next release.
