### ISSUE TITLE
Ship combat UI usually disappears

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#113]
When I meet a ship combat, my ship combat UI usually disappears as title. I'm uploading my game video on Bilibili. This really plague me a lot. I 'll provide more information if needed.

**Comment by WhiteGiverMa** [comment]
@SonicTHI 
This is the major issue I met in the process of video uploading. Unfortunately, there are also massive 'minor' issues too.
https://www.bilibili.com/video/BV1ne411H7hA
Here are my videos. I don't mean to trouble you to go see it if you dont want to, I just want to tell you, **if you're willing to listen to me, I can arrange and list the bugs I met in English in each of my videos, and you can choose to check and fix it according to your mood.** I 'll put the bug lists in the introductions under my videos if you need them, and you can easily find them.
How does this sound?(・ω< )★

**Comment by SonicTHI** [comment]
Put reports here with logs and video time and i ll look at them.

**Comment by WhiteGiverMa** [comment]
> Put reports here with logs and video time and i ll look at them.
> 
> Also i uploaded a copy of the dev sheet [here](https://www.mediafire.com/file/5uwtj2xt52bamxg/SOS2_Experimental.xlsx/file). Hope you can access it.

@SonicTHI OK, I can access it(・ω< )★, thanks a lot. But I didn't find something like change log in it, maybe I'm a little fool?(〃ﾉωﾉ)
https://www.bilibili.com/video/BV1ne411H7hA
At 24:40 of this video, I try to move my ship but failed, and some of my floor disappears. In the beginning of next video (there is a video list on the right), you can see the sterile tile disappeared.
The bug is in V97. Because I didn't find the change log, I 'm not sure if it's fixed. Some other bugs are the same. May I know where I can find the change log? Thank you a lot, I like you(*๓´╰╯`๓)♡

**Comment by SonicTHI** [comment]
That is the change log, i dont track every single change,, you can see those on git.
What i need from you are [full logs](https://github.com/SonicTHI/SaveOurShip2Experimental/issues/65) when these errors happen.

**Comment by WhiteGiverMa** [comment]
> That is the change log, i dont track every single change,, you can see those on git. What i need from you are [full logs](https://github.com/SonicTHI/SaveOurShip2Experimental/issues/65) when these errors happen.

Oh, I'm so sorry for forgetting to make a copy of the log at that time. It's several days ago, and the log may include something that disturb your judgment. I'm really sorry for it (｡í _ ì｡)
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13999665/Player.log)
[Player-prev.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13999666/Player-prev.log)

**Comment by gpaschoaletto** [comment]
I have experienced the same error a few times. While I'm not sure if it helps, I noticed that if I simply save-reload the game, the battles go back to working.

**Comment by SonicTHI** [comment]
Should be fixed in V97f3. If it still occurs submit a new report.
