### ISSUE TITLE
Enemy's projectiles are stilled and I can't win the battle as a bug

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#115]
https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/8058061f-09f6-4b12-9439-0dcc5bbedc08

In this video, after defeating the Orion Class Battlecruiser, the bug occurs on the Aurora Class Battlecruiser.
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14000067/Player.log)
[Player-prev.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14000070/Player-prev.log)
These are the logs. The previous Included, is it OK?
Thanks a lot (*๓´╰╯`๓)♡

**Comment by SonicTHI** [comment]
Should be fixed in V97f3. If it still occurs submit a new report.
