### ISSUE TITLE
Can't abandon wrecks and my ship "seperates"after save&load

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#116]
https://www.bilibili.com/video/BV1YZ4y1J7Rn
At 00:28 in this video, I couldn't abandon the wrecks when the battle began. After I made a save&load, my ship "seperates". It's very strange. Is my log needed?

**Comment by WhiteGiverMa** [comment]
By the way, the bug occurs in V97f1. Maybe it's fixed?

**Comment by SonicTHI** [comment]
Should be fixed in V97f3. If it still occurs submit a new report.
