### ISSUE TITLE
Enemy retreats in an active attack and identifying mistakes

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#118]
https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/0ee7d7c8-46b9-440d-a625-d2bab0a89a93

As the video. It's not a normal phenomenon, I think.
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14037248/Player.log)
This is the log.

**Comment by WhiteGiverMa** [comment]
Because of this, I can hardly normally play this mod now.(இωஇ )

**Comment by SonicTHI** [comment]
Enemy ship calculated its threat wrong. Not sure how this happened and it does not seem to be a cache issue. Let me know if it happens again.

**Comment by WhiteGiverMa** [comment]
> Enemy ship calculated its threat wrong. Not sure how this happened and it does not seem to be a cache issue. Let me know if it happens again.

@SonicTHI It still happens, retreating in an active attack. What's more, they are at absolute advantage. As this video.

https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/0a9074a6-d302-45db-b7b0-4f770fa81c43

[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14070780/Player.log)
This is the log.

**Comment by SonicTHI** [comment]
I cant replicate this on my end. Might be a mod conflict, something that interacts with buildings/power.
