### ISSUE TITLE
Research Reinvented + Harvest Organs Postmortem + SaveOurShip2 = Issue

### ISSUE THREAD

**Issue by fwhs2000** [SonicTHI/SaveOurShip2Experimental#120]
Research reinvented demands that I use the depreciated hologram corpse to research the organ harvesting techs.

![screenshot1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/58830465/82ee2cf5-92fd-44e1-a5cd-be7fd0daad3d)

The Hologram meat could also be an issue, but isn't for my mods.

**Comment by SonicTHI** [comment]
These were left in for backward compatibility and cleanup but as it has been over a year since 1.3 i ll remove them.
This might be baked into your save though and will likely cause issues.
Try and remove SoSHologramRace from 1.4\Defs\PawnKindDefs\PawnKinds_Space.xml.
