### ISSUE TITLE
Nutrient Paste Dispenser doesn't work upon ship location change

### ISSUE THREAD

**Issue by ZacharyDK** [SonicTHI/SaveOurShip2Experimental#125]
Circumstances:
1. Bug only occurs with RimThreaded, OR other possibly conflicting mods on the modlist.
2. With the vanilla mod manager: Didn't occur when I disabled nearly every extraneous mod and loaded a new save with bare bones modlist. The player logs will confirm whether my mod trimming was successful - I don't fully trust Rimworld to be honest about what mods are active, so you'll have to read the logs to fully confirm if my trimming was successful.
3. Bug didn't occur with a small test ship, but it may occur with a large ship.

Replication:
1. Have a ship with a nutrient paste dispenser. 
2. Change the location of the ship. Happens from ground to orbit, orbit to ground, or move ship in orbit.
3. After the location of the ship has finish, there will be a notification that a nutrient paste dispenser needs a hopper. 
4. The nutrient paste dispenser doesn't recognize the hoppers that are fully attached.  Pawns won't use the dispenser even though there are hoppers attached with food. 
5. Deconstructing and Rebuilding the hoppers doesn't fix the issue. You have to deconstruct and rebuild the nutrient paste dispenser every time you move the ship to fix the dispenser.

Logs:
[PasteBugLog.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14240460/PasteBugLog.log)
[PasteWorkingPlayer.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14240467/PasteWorkingPlayer.log)

PasteBugLog has the bug replicated on my current play through with whatever mods I have.
PasteWorkingPlayer - bug doesn't occur when I attempted to curate my modlist on a new test save. Maybe I was successful.

[NutrientPasteWorkingSave.rws.zip](https://github.com/SonicTHI/SaveOurShip2Experimental/files/14240490/NutrientPasteWorkingSave.rws.zip) Small save with a quirk dev ship on world load. Paste dispenser works after launching the ship into orbit. 

<img width="932" alt="Screenshot 2024-02-12 at 10 49 11 AM" src="https://github.com/SonicTHI/SaveOurShip2Experimental/assets/40034922/c7c5d99a-a3ef-4285-b886-95e885dfdb8f">

This the mod list I tried to cut down to for testing. I felt this was representative testing environment for what mods players would have while playing SOS2. Current play through has Vanilla expanded mechanoids, but it was not available in mod options for my test save so maybe I successfully disabled it for that save. But on Rimworld start up, my modlist from my current play through was selected and no notice about change in modlist for my test save when I selected it. Point is testing is a bit difficult when I'm not sure if a problem mod is loaded...

***

If the cause is RimThreaded, and the fix is easy, I would highly appreciate a fix. I understand compatibility with RT isn't a priority. Thanks.

**Comment by SonicTHI** [comment]
if it is not reproducible with vanilla+SOS2 it will not be worked on.

**Comment by ZacharyDK** [comment]
Fair enough. Can you explain in simple terms what objects might be related to bug from what you can glean from the player logs? I want some context for what objects I can inform the RT to look at. Like here I can say peak at the ship movement as a starting point, but I have no such context to make the lives of RT team easier. Only 90% certain that problem is related to RT, as it has been known to cause issues in the past. And my knowledge about reading these .log files is very limited. 



I can code and attempt to patch it myself (longshot) - but I would need insight as to whether or not you think its a simple fix. I.e how would you begin to fix it after 15 min of reading the logs? My C sharp and Rimworld modding experience is zero, so anything off the deep end is a no go.
