### ISSUE TITLE
SOS2 + GiddyUp Trader Issue

### ISSUE THREAD

**Issue by Lord-Sputnik** [SonicTHI/SaveOurShip2Experimental#131]
With archo life now requiring an archotect, any traders riding an archotech animal with disappear when entering the player map potentially causing the trader to lose goods as well as the trader itself.

**Comment by DoggoElDoggo** [comment]
I haven't tested this, but this could be a decent temporary fix.
If you have OwlChemist's Cherry Picker, (https://steamcommunity.com/sharedfiles/filedetails/?id=2633276599) you can prevent any archo animals from spawning at all. This will prevent them from spawning in caravans and causing the issue. You can then re-enable them spawning when you have the Archotech Spore. Hope this helps!

**Comment by SonicTHI** [comment]
Added to partial comp mod list with solution.
