### ISSUE TITLE
1.5 Dubs bad hygiene incompatibility 

### ISSUE THREAD

**Issue by ZacharyDK** [SonicTHI/SaveOurShip2Experimental#134]
In Rim World 1.5, the life support systems no longer produce water. Please update the development sheet to reflect this. Using escape planet ending in 1.4, and using it to start a new colony does let the 1.5 ship have water pipes that come with placing ship hull. 

[MostlyStandalone.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/15049946/MostlyStandalone.log)
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/15049947/Player.log)

Note - deleting and rebuilding the life support systems does NOT fix the issue. Adjusting mod load order does not fix it either. 

Something about name space changing...

I don't know if it is possible to test if another mod looks for the old name space, and redirect it to the new name.

**Comment by LeoSoiBoi** [comment]
Having the same issue with a new game as well
