### ISSUE TITLE
Mechs sometimes unable to self-shutdown after V78f1 version

### ISSUE THREAD

**Issue by Kazuhito9702** [SonicTHI/SaveOurShip2Experimental#31]
https://gist.github.com/HugsLibRecordKeeper/e5f7f96ba663778d0bd8e7dbdabc3daf
Full error log

I was using 4fd4375 build(somewhere after the v77f1) of this mod and was finding a fix for mechs trying to sleep on the void, not on the ship floor.
I found out there is a new patch to fix this and downloaded the v78f1 version.
Thankfully, it worked and my mechs now don't try to move all the way out of the ship and just stay still on the plating.
But there came out a new issue where they don't sleep when two or more mechs are in one spot.
This would not be an issue when one does not have many mechs or when mechs keep moving and do their job.
They tend to disperse when they are drafted too.
However, when they try to charge at the mech charger or haul things into one spot and they finish their job, they try to sleep at the same spot and it gives me red messages.
Instead of sleeping, they just stand there, showing that they are 'waiting' until they get a new job or the previously sleeping mech wakes up and move out.
On the error log, it just talks about mechs from Miho mod, but it is just because most of the mechs I use are Miho mechs and vanilla mechs like constructoids or cleansweepers(ex. log line 8167-8169) also give me the same error.

I personally think that the error occured because of this part of the patch, but don't know how to actually fix this.

for (int i = 0; i < GenAdj.CardinalDirections.Length; i++)
				{
					List<Thing> thingList = (c + GenAdj.CardinalDirections[i]).GetThingList(map);
					for (int j = 0; j < thingList.Count; j++)
					{
						if (thingList[j].def.hasInteractionCell && thingList[j].InteractionCell == c)
						{
							return false;

**Comment by Kazuhito9702** [comment]
Could not reserve (127, 0, 131) (layer: null) for Mech_Constructoid11297 for job SelfShutdown (Job_1082) A=(127, 0, 131) (now doing job SelfShutdown (Job_1082) A=(127, 0, 131)(curToil=-1)) for maxPawns 1 and stackCount -1. Existing reserver: Mech_Constructoid11280 doing job SelfShutdown (Job_1056) A=(127, 0, 131) (toilIndex=1)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.ReservationManager:LogCouldNotReserveError (Verse.Pawn,Verse.AI.Job,Verse.LocalTargetInfo,int,int,Verse.ReservationLayerDef)
Verse.AI.ReservationManager:Reserve (Verse.Pawn,Verse.AI.Job,Verse.LocalTargetInfo,int,int,Verse.ReservationLayerDef,bool)
Verse.AI.ReservationUtility:Reserve (Verse.Pawn,Verse.LocalTargetInfo,Verse.AI.Job,int,int,Verse.ReservationLayerDef,bool)
RimWorld.JobDriver_SelfShutdown:TryMakePreToilReservations (bool)
Verse.AI.Pawn_JobTracker:StartJob (Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool,System.Nullable`1<bool>,bool,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()

**Comment by Kazuhito9702** [comment]
and a yellow error follows:
TryMakePreToilReservations() returned false for a non-queued job right after StartJob(). This should have been checked before. curJob=SelfShutdown (Job_1082) A=(127, 0, 131)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.AI.Pawn_JobTracker:StartJob (Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool,System.Nullable`1<bool>,bool,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()

**Comment by Kazuhito9702** [comment]
It also happens when I only put Core, Royalty, Ideology, Biotech, Harmony, Hugslib, SOS2, Wall Light

**Comment by SonicTHI** [comment]
fixed in V78f3
