### ISSUE TITLE
Archolope doesn't produce exotic particles

### ISSUE THREAD

**Issue by KyleKrein** [SonicTHI/SaveOurShip2Experimental#41]
The description says that Archolope produces exotuc particles, but in fact the only interaction available is training. And there's no indicator that "milk" production in process

**Comment by KentHaeger** [comment]
Is the archolope fully grown? Like all animals, it doesn't produce "milk" until it's an adult.

**Comment by KyleKrein** [comment]
It's 2 years old already. At some point it started producing exotic particles. But then I saved the game and loaded save. After this, archolope stopped producing exotic particles again.
