### ISSUE TITLE
CE **IS** compatible 

### ISSUE THREAD

**Issue by T-rexsuper1** [SonicTHI/SaveOurShip2Experimental#47]
In the about section it lists Combat Extended as one of the incompatible mods. This information is false. I have tested space combat and boarding. Both work with CE perfectly. Ship cannons work. Everything does. Old patch still holds up. 
Please, remove Combat Extended from the list of incompatible mods.

**Comment by SonicTHI** [comment]
Ground defense weapons do not work properly and there have been changes in the way our projectiles handle. Until whoever is responsible for the CE patch fixes and confirms that it stays as is.
