### ISSUE TITLE
Suggest/Propose tweak to method ShipInteriorMod2.EVALevelSlow

### ISSUE THREAD

**Issue by MasterOfGrey** [SonicTHI/SaveOurShip2Experimental#49]
Hi folks, hopefully this doesn't step on anyone's toes!

Bit of background to this; I've come from the Android Tiers Reforged server where regularly a couple of people come through asking about Androids needing to breathe in space.

At present all the standard tiered androids still require appropriate vacuum protection gear to get about in space.
There's a submod out there somewhere that makes them all just automatically not need to breathe in space, but that's not a feature that the authors consider to be desirable. They are after all, complex machines built to work in a people-safe environment.

Rather than putting them in a space suit or coming up with some kind of android-only gear though. It'd make a fair amount of sense if they could be upgraded to be vacuum-hardened since they are androids, and there's also existing mechanics and such for there to be a sensible and lore friendly upgrade option added to the ATR mod pretty trivially.

Except at the moment, it wouldn't work.
For it to be an upgrade option it would need to be a hediff, or some value added by a hediff, but the method only looks for 2 *general* values: a trade tag that has to be part of the base racedef, or an EVA value that only works on apparel thingdefs.
Every other option that the method looks for to allow safely operating in space is hard coded.

There's a moderate chunk of content we could add if the option were available though.

Now this *could* be patched on the ATR side of things. We had a bit of a discussion and some conclusions were reached:
> There's really only two good approaches to a patch you could do to achieve this without bricking things:
> - Accept this method and add your own hardcoded HediffDefOf and use a Postfix to return a specific number if a pawn has the hediff. In this case, I'd say that HediffDefOf would point at a new framework Hediff.
> - Rewrite it using a Prefix checking against a wider range of values by patching a DefModExtension onto Hediffs with some sort of tagger for its EVA status allowing you to apply it to any range of Hediffs and have them all work, sort of how the method is currently scanning apparel.

I should note here that I'm not personally experienced with C#, so I don't know if those *are* the only two ways, but that's what the coder peeps came up with.

However, the feeling in the conversation was that neither of these were particularly *good* options. The thinking was that this method could probably be re-done in a more flexible way;
There are certainly advantages to the way it is currently written - I'm sure having it return unique values for different cases has a number of potentially advantageous downstream uses, and it's very parsable which is certainly nice - but the thinking was still that (respectfully) it could be rewritten in a better way to output the same with more flexibility.

It was also felt that a direct change on the SoS2 side of things would be considerably more performant and *much* more stable than trying to patch that from outside.

### **Suggestion/Proposal:**
So the proposal is to rework the method to either take some value which can be applied by a hediff, or to match against some list of hediffs. Either case the goal being to return an EVALevel that would allow something to be dynamically made spaceproof by upgrade methods other than just the archotech skin and lungs combination.

We're hoping that you might be amenable to making that sort of change?
(Or, if you're very busy, if you might be ok with us putting together a PR to change it?)

**Comment by SonicTHI** [comment]
Best would be for one of your coders to join the RHX discord so we can talk about how a possible PR could look like.
