### ISSUE TITLE
Deleted then updated to new version but now my ship is non functional and have black background

### ISSUE THREAD

**Issue by Jamiesauce12** [SonicTHI/SaveOurShip2Experimental#54]
Hi, deleted old verision, then updated to new one. Now the space background is completely black, and the ship is as if it hasn't launched. It is saying it's missing critical components that it didn't need before. And i can't fly it. Sorry to be a pain. Thanks for the hard work!
![image](https://user-images.githubusercontent.com/129075175/228201005-5034e254-0c32-453f-9222-c92a264564de.png)

![image](https://user-images.githubusercontent.com/129075175/228200787-509d9eda-6478-4a1d-a14b-8a98ffe94e52.png)

**Comment by SonicTHI** [comment]
fixed
