### ISSUE TITLE
Map doesn't generate when loading new ship

### ISSUE THREAD

**Issue by Jamiesauce12** [SonicTHI/SaveOurShip2Experimental#56]
Sent my ship off on an adventure to new planet. Started new world, wanted to load ship, the map doesn't generate, just on the world option screen. generates it and then goes back to the world option screen.

Hope the bug reports are helping 👯

**Comment by luner2001** [comment]
I can confirm this issiue, but as a mod incompatibility issuie. With SOS2 and no other mods installed, this error doesnt happen for me. But the Vanilla Expanded Framework, for sure breaks the ship load start. Ive got a few mods that do this, trying to figure out all the ones that do.

**Comment by SonicTHI** [comment]
Should be fixed in latest, if not open a new issue with a log.
