### ISSUE TITLE
Better patch naming and formatting

### ISSUE THREAD

**Issue by MatthewTeply** [SonicTHI/SaveOurShip2Experimental#6]
## Description
Patch file names are a mess, unify their naming. Some of them also have really messy XML formatting, make them more readable.

## Implementation
Rename and format XML patches.

**Comment by SonicTHI** [comment]
That goes for pretty much every part of the project and its been kept that way for easier integration into the steam build in the past. At this point however i dont care about that anymore - if you want to do some cleanup go ahead and i ll merge it. The only thing to keep in mind is anything that relates to saving/backwards compatibility that must be kept intact.

**Comment by SonicTHI** [comment]
Fixed in V72
