### ISSUE TITLE
"Revisiting old planets is no longer possible" workaround suggestion

### ISSUE THREAD

**Issue by ricomaster9000** [SonicTHI/SaveOurShip2Experimental#61]
So I was about, trying to fix a SOS2 harmony patch and it kept breaking because a certain "world switch" method does not exist anymore.

Now I understand why, I think this adds a shit ton of possible bugs and just complicates it a lot, BUT...

Would it not be possible to re-apply what you did for going to a new world, the end-game-start-scenario way to revisiting old worlds.

I think this won't ever be able to re-create a exact replica of the old world but maybe certain things like map biome exact locations and world map generation data could be re-used, maybe the exact factions you had could be re-used, and also how many settlements etc. they had.

You're exact map will probably not exist anymore, but at the very least you play on the exact same world as last time, with the exact same factions and their relative strength, this could be a good starting point.

This does in a basic way cover revisiting old worlds and I can think of some nice reasons people would want to do this, for instance they fled their old world because it was overrun by machines/insects, so now they are prepared to push back and re-take the world and revisit it again, something like this. Other mods can then patch on this method etc.

**Comment by SonicTHI** [comment]
You ll be able to use the same hash to generate the same planet. Not sure how factions work in that context but i guess using the exact same ones should have the same result. Beyond that, too much work.
