### ISSUE TITLE
incompatibility with 'Vanilla Helixien Gas Expanded' mod

### ISSUE THREAD

**Issue by matrixarg** [SonicTHI/SaveOurShip2Experimental#71]
hello. A few versions ago of your mod, a notice of incompatibility with the Vanilla Helixien Gas Expanded mod began to appear, for which I have attached the access link. Could it be due to an error in one of the mods? thanks in advance
https://steamcommunity.com/sharedfiles/filedetails/?id=2877699803

**Comment by matrixarg** [comment]
![1111](https://user-images.githubusercontent.com/88107336/236647370-2f472d39-b10d-4337-bd09-4bdca7caa41f.JPG)

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Very nice how you close this but don't even say a word about why this is happening, if it's on your end or theirs, if it's a serious issue or something minor, etc.
