### ISSUE TITLE
Constructing EVA Suits from different materials doesn't give any variation in item stats.

### ISSUE THREAD

**Issue by stubkan** [SonicTHI/SaveOurShip2Experimental#80]
Constructing EVA Suits from different materials doesn't give any variation in item stats.

The EVA Suit can use multiple fabrics as a component, contributing to a majority of its makeup.  Ie, cloth, devilstrand, synth or hyperweave.  All variations end up with a suit that have the same default values - with no material derived increase/decrease in armor, temperature resistance, price, beauty, hitpoints, etc.

It would be beneficial to gameplay if the materials contributed to the suit makeup like normal apparel does - allowing players to min-max by using the best materials available, otherwise you might as well use the worst material you have, as the output is irrelevant.

Screenshot provided of materials available, showing an EVA suit propsal bill with all default values

![screenshot-20230718-202824](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/34361592/998ff415-0e24-4aff-b815-12c332310c54)

**Comment by stubkan** [comment]
How about these values for the EVASuit and Kid EVASuit

<StuffEffectMultiplierArmor>0.2</StuffEffectMultiplierArmor>
<StuffEffectMultiplierInsulation_Cold>0.4</StuffEffectMultiplierInsulation_Cold>
<StuffEffectMultiplierInsulation_Heat>0.4</StuffEffectMultiplierInsulation_Heat>

Which will enable fabric value inheriting... Then these values below to encourage using good materials

<Insulation_Cold>85</Insulation_Cold>
<ArmorRating_Blunt>0.3</ArmorRating_Blunt>
<ArmorRating_Sharp>0.3</ArmorRating_Sharp>

Default EVA suit of cloth will be underwhelming and default.  Getting higher quality and good materials, will improve the suit but it will not be as good as Heavy EVA or Marine armour.

**Comment by SonicTHI** [comment]
Another old problem. This could make normal suits better than the heavy variant. Stuffing is only kept due to legacy compatibility.

**Comment by stubkan** [comment]
In my tests, a hyperweave masterwork EVA suit just reached the quality of a normal heavy EVA suit with the settings I suggested - If the concern is not to surpass the heavy - that can be implemented easily.
