### ISSUE TITLE
Error while generating a map -> Incompatibility with the Empire mod as of now.

### ISSUE THREAD

**Issue by paranoidsr** [SonicTHI/SaveOurShip2Experimental#84]
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/12312979/Player.log)

Dear modding team,

Currently I observe a failure to generate a new map (new game) with the mod Empire (listed as having integrated compatibility in the wiki.)

Versions of the Empire mod used:
https://github.com/Danimineiro/Empire-Mod/tree/1.4 85ee9e7

and continued steam version: mod 3017452577 updated on 10 Aug 12:54pm

I have made sure that the downloaded version of SOS2 is the commit e9226f9, unfortunately the log lists V91f2.

The replication should be trivial; the point of failure is right after the player confirms the "crash site" and expects to be loaded into a local map.

Let me know if I can assist in any way.

**Comment by SonicTHI** [comment]
Wiki is outdated, use the sheet.
