### ISSUE TITLE
Strange NotImplementedException Error

### ISSUE THREAD

**Issue by lisanhu** [SonicTHI/SaveOurShip2Experimental#86]
Hi! Thanks for the great mod.

Today, I started to add SOS2Exp to my mod and after my first ship fight, I received this strange error. Could you please help me with this problem? Really appreciate it!

Mod list: Harmony, Core and all DLCs, Wall Light, SOS2Exp (nothing else)
Version: V91f3

Exception:
```
Exception ticking ShipMoveBlueprint-1 (at (135, 0, 116)): System.NotImplementedException: The method or operation is not implemented.
  at Verse.Entity.Tick () [0x00000] in <badc476ef0d446b498e5b20480e435f8>:0 
  at Verse.TickList.Tick () [0x0015c] in <badc476ef0d446b498e5b20480e435f8>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
```

I could not provide the full log because there's no Files and Open Save Folder in my log window (probably because I'm not activating HugsLib? I'm not sure)
I'm providing my save file for you to reproduce the problem easier
[https://drive.google.com/file/d/1An1fFDqeXgMKtV-GN9cxCyLngwan_rlp/view?usp=sharing](https://drive.google.com/file/d/1An1fFDqeXgMKtV-GN9cxCyLngwan_rlp/view?usp=sharing)

Thank you so much for taking a look at this

**Comment by SonicTHI** [comment]
Took a look at the save and it might be a language/translation issue of some sort. No idea beyond that.

**Comment by lisanhu** [comment]
Thanks for looking at it. It's very strange. Everything's normal when using a new save, and everything's broken with my save :(  , probably there's some strange conflicts somewhere.

Thank you again for looking at this issue.
