### ISSUE TITLE
I cant claim the imperial destroyer that I got from finishing the royalty ending.

### ISSUE THREAD

**Issue by Milo74237** [SonicTHI/SaveOurShip2Experimental#87]
I cant claim the imperial destroyer that I got from finishing the royalty ending there fore I am not able to move the ship or anything.

**Comment by SonicTHI** [comment]
Without any further info and [proper bug reports](https://github.com/SonicTHI/SaveOurShip2Experimental#faq-troubleshooting-and-issue-reporting) i cant help you.

**Comment by ILanOreX** [comment]
Maybe i can provide a proper bug report to this issue. I have the same problem. The royal ascend quest doesnt award a ship. It just turns the screen white, map still running in the background and when you press esc you're back but nothing spawned in orbit and the quest seems to be completed. I looked at the dev sheet and saw that the "Player has to manually drag his ass over to the ship". I tried diffrent scenarios. Dragging the stellarch/forcing him in by himslef/Launching him solo/not solo. Maybe im missing something, so im prividing my save and player log. I installed SoS2E on an existent save.
Thank you!

![20231123173803_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/151864203/c444415c-3fee-480a-963d-ad01e54b8233)
![20231123173814_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/151864203/db11b906-a1ec-4da8-a6aa-8ad26cb4296a)
![20231123174011_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/151864203/413d9782-5b6d-4a71-8e55-c51cabff4793)
![20231123174017_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/151864203/2b9945e8-d230-4101-b2f3-33fb36eb1393)
![20231123174033_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/151864203/d090a644-4fa3-4400-b9ae-cb2abce5825a)


Im on: V92f2 Modlist: 
Harmony/Core/Royalty/Ideology/Biotech/[FSF] Filth Vanishes With Rain And Time/[HRK] Vanilla Expanded Extra Embrasures/>RimFridge Updated/LWM's Deep Storage/[JDS] Simple Storage/Armor Racks/Auto Light Switch/>CleaningArea/CM Color Coded Mood Bar [1.1+]/Common Sense/EdB Prepare Carefully/Pick Up And Haul/Replantable Anima Trees/Replantable Gauranlen Trees/RimHUD/RT Fuse/Share The Load/Smart Farming/Subsurface Conduit/Wall Light/Rah's Vanilla Turrets Expansion/Save Our Ship 2

https://drive.google.com/file/d/1vc2HqwSGrwAd2K0k51TYGH5cVD-E8qrt/view?usp=sharing

[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13452312/Player.log)

**Comment by SonicTHI** [comment]
Sorry for the late reply.
We do not support beta versions of RW but the likely case seems to be that you added SOS2 post generating the royal quest. Since RW saves quest stages, those can not be altered by mods thereafter. I will add that info on the feature/dev list.
