### ISSUE TITLE
How do I download it?

### ISSUE THREAD

**Issue by Dolphinwithinternet** [SonicTHI/SaveOurShip2Experimental#89]
There are no releases, and the instructions don't actually say how to download it i tried just downloading the entire thing but rimworld says it's not made for this version of rimworld and there's no description so i assume it didn't work.

**Comment by unknown-user397** [comment]
first you need to download the zip file then unzip it and i think you put the unziped file into the modloader thing

**Comment by SonicTHI** [comment]
https://github.com/SonicTHI/SaveOurShip2Experimental#installation-and-updating

**Comment by cooljacob204** [comment]
So I was also confused by this I was expecting a release or a button in the readme up top. Took me a while to realize it mean download the repo.

Might I suggest just adding this link into the readme itself?

https://github.com/SonicTHI/SaveOurShip2Experimental/archive/refs/heads/main.zip
