### ISSUE TITLE
Launch ship button does not appear with large ship

### ISSUE THREAD

**Issue by EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE1** [SonicTHI/SaveOurShip2Experimental#9]
When construction of a fairly large ship was completed on the surface, the launch button did not show up, and I cannot open the launch report, ship is fueled, all needed components are there and powered, and ship info shows that I should be able to launch just fine, but the launch button does not even show up

Problems do not happen with small ships

Error log only spits out a single one-time error saying System.NullReferenceExeption: Object reference not set to an instance of an object a SaveOurShip2.FindLaunchFailReasons.FindLaunchFailReasonsReally

![Error](https://user-images.githubusercontent.com/64393404/200143909-cb7132ba-a3fd-48ad-a4a1-6230f3b20b7d.JPG)

**Comment by EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE1** [comment]
Source located: Johnson-Tanaka drive, actual cause still unknown

**Comment by KrzysztofKowalski** [comment]
> When construction of a fairly large ship was completed on the surface, the launch button did not show up, and I cannot open the launch report, ship is fueled, all needed components are there and powered, and ship info shows that I should be able to launch just fine, but the launch button does not even show up
> 
> Problems do not happen with small ships
> 
> Error log only spits out a single one-time error saying System.NullReferenceExeption: Object reference not set to an instance of an object a SaveOurShip2.FindLaunchFailReasons.FindLaunchFailReasonsReally
> 
> ![Error](https://user-images.githubusercontent.com/64393404/200143909-cb7132ba-a3fd-48ad-a4a1-6230f3b20b7d.JPG)

i had same with lots of other mods

after using only sos2 it works so something else might cause it
