### ISSUE TITLE
Posh thank you thread

### ISSUE THREAD

**Issue by Normal69** [SonicTHI/SaveOurShip2Experimental#96]
May chaos smile on _you_ by chance, and praise the Emperor who graciously keeps up the beacon of You, _making this_ mod.
May you be _so kind_ to let me estabilish this holy place - I'm still striving to reach across galactic space to land on dirt which nurtures the seeds of my little group's ideas (haven't reached your mod's scope, but it's inspiring being there).

By the way how do you endorse making a collection with this mod-version?
Link steam one as usual then cross-refernce the link in the faq part of the description of the collection to reward people who actually care?
Well, I'm not advising  just mentioning that's the custom on my spacehulk.

Or, as slow am I to test, it will be on steam earlier than that point in time?
Most probable.

Win-win. :)

**Comment by SonicTHI** [comment]
Yes, that is fine. The page and mod ID will stay the same after SOS2 1.4 Steam release (again: no ETA on that).
You would only need to alter the collection description after.
