### ISSUE TITLE
Strange hard crash - generation of one type of asteroid map

### ISSUE THREAD

**Issue by LordHavoc01** [SonicTHI/SaveOurShip2Experimental#97]
[Sos_debug_2023.zip](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13559092/Sos_debug_2023.zip)

I'm experiencing a hard crash when entering 'one' type of asteroid site (I'm hoping it's just one type, I don't know how many types there are in total).
I've seen working at least 4 generations of asteroids, so know its not a universal issue; I'm thinking there is something unique about the crashing one which might be conflicting with a mod I'm running with.

I've attached my modlist and highlighted (encased in three ###) the mods I've already tried eliminating which to my knowledge effects mapgen. Note: I've looked into the code for Cupro's Alloys and it's "very basic" ore gen, I can't see it being that...plus it works with the other asteroids.

Could someone glance over my mod list and if any 'jump out at you' at being the cause of a hard crash, please let me know.

I'm not asking for a large amount of time on this; so any you can spare would be hugely appreciated.

**Comment by LordHavoc01** [comment]
I've been able to identify which quest causes the crash. It appears to be ones which require 14% shuttle fuel. I've attached screenshots.
The one which required 25% fuel worked fine. But both 14% ones crash
![rimbug_1](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/142110324/43f70fb3-9264-440c-af00-bf36b8669565)
![rimbug_2](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/142110324/0f0e1fbf-177e-4872-b1e8-d6491659dd63)
![rimbug_3](https://github.com/SonicTHI/SaveOurShip2Experimental/assets/142110324/4a5e1d9a-3f36-43af-a313-d0a042127373)

**Comment by SonicTHI** [comment]
Likely one of your 250 mods as legacy RW code is used to gen these. Try and replicate in vanilla + SOS2. If you cant, you ll need to find the mod causing the issue.
